title: Start with GitHub
description: >-
  On this course @SofianeHamlaoui will teach you the fundamentals of the Version
  Control System and Github. This course is designed for Algerians to make them
  more comfortable with the world of Open Source. Made by the @dzcode-io team
  for Algerians ♥️ .
template:
  repo: start-with-github-template
  name: start-with-github
before:
  - type: createIssue
    title: Create An Issue!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
